      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: SonarQube Scan
        run: |
          mvn clean \
              -Dcheckstyle.skip=true \
              -Dmaven.javadoc.skip=true \
              org.jacoco:jacoco-maven-plugin:prepare-agent \
              package \
              verify -Dgpg.skip=true \
              org.jacoco:jacoco-maven-plugin:report \
              org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
              -Dsonar.organization=alexjferreira \
              --file pom.xml -B --no-transfer-progress
        env:
          SONAR_TOKEN: ${{ secrets.SonarCloudToken }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
